Tweak script: install-sys-deps
As per feedback from @AndreaCrotti in #238 — thanks Andrea!

diff --git a/tool/bin/install-sys-deps b/tool/bin/install-sys-deps
--- a/tool/bin/install-sys-deps
+++ b/tool/bin/install-sys-deps
@@ -8,6 +8,11 @@ set -eux
 
 OS="$1"
 
+if [ "$OS" == '' ]; then
+  echo 'ERROR: OS must be specified as first arg; see the source of this script for accepted values.'
+  exit 1
+fi
+
 case "$OS" in
 'linux-arch')
   # We’re using sudo in /bin/install-clojure
@@ -24,6 +29,6 @@ case "$OS" in
   echo 'TODO'
   ;;
 *)
-  echo 'ERROR: OS must be specified as first arg; see the source of this script for accepted values.'
+  echo "ERROR: $1 is not a supported OS; see the source of this script for accepted values."
   exit 1
 esac
